# Generated by Django 4.0.1 on 2022-02-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blogimage',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
